src/app/app-routing.module.ts
src/app/app.module.ts
src/app/pages/available-cities/available-cities.component.html
src/app/pages/available-cities/available-cities.component.spec.ts
src/app/pages/available-cities/available-cities.component.ts
src/assets/pages/available-cities.json
src/assets/pages/home.json

Adiciona página de cidades disponíveis

---

src/assets/pages/support/community.json

Corrige contagem de pessoa que fizeram contribuições financeiras e adiciona nome de novo contribuidor

atualiza informações de contribuição

---

src/assets/pages/available-cities.json
src/assets/pages/home.json
src/assets/pages/notifications.json

Este PR:
- atualiza contador de cidades 
- atualiza o sininho de notificações
- atualiza a lista de cidades

Atualiza informações de 6 novas cidades

---

src/app/gazette.service.ts

Corrige codificação de URL de requisição para API

---

README.md
package.json
src/styles.sass
tailwind.config.js
yarn.lock

- Instalando este framework CSS para facilitar as atualizações das issues, principalmente para cobertura de responsividade entre dispositivos, não precisando criar regras customizadas.
- Não é necessário instalar o `@angular/cli` globalmente uma vez que ele já está instalado no projeto.
- Basta usar o script já configurado
- Havia um alerta e pesquisando, vi que esta dependência é necessária apenas para desenvolvimento.
```
warning package.json: "dependencies" has dependency "@angular/cli" with range "^11.2.10" that collides with a dependency in "devDependencies" of the same name with version "~11.2.10"
```
---
[**English**]
- Installing this CSS framework to make the issues update easiser, especially to cover the devices responsivity, not needing to create custom rules.
- It's not …

Instala o TailwindCSS | Install TailwindCSS

---

src/app/pages/search/search.component.html

adiciona mensagem de resultados não encontrados sem termo de busca

---

src/assets/pages/available-cities.json
src/assets/pages/home.json
src/assets/pages/notifications.json

Este PR faz as atualizações em informações do site do QD devido a entrada de novas cidades no projeto.
A data de `notifications.json` está para amanhã (07/10) pois apenas amanhã que faremos o anúncio público que tem novas cidades.

Atualiza informações referentes às 5 novas cidades em produção

---

src/assets/pages/home.json
src/assets/pages/notifications.json

- 14 novas cidades foram adicionadas no querido diário; este PR atualiza o site com suas informações

Atualiza site devido adição de cidades

---

src/assets/pages/home.json
src/assets/pages/notifications.json

O PR atualiza contador de cidades na home e as notificações

Atualiza site com informações de nova cidade

---

.github/ISSUE_TEMPLATE/NEW_POST.yml

Corrige issue template NEW_POST.yml

---

src/assets/pages/home.json
src/assets/pages/notifications.json
src/assets/pages/support/community.json

Adiciona novas cidades e pessoa contribuidora

---

src/assets/pages/home.json
src/assets/pages/notifications.json

Adiciona novas cidades (jun/23)

---

src/assets/pages/home.json
src/assets/pages/notifications.json

Adiciona 14 novas cidades da Sprint da Amazônia Legal

---

src/assets/pages/home-education.json

|Antes|Depois|
|--|--|
|![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/26327506/3a5faf3e-81af-42e4-b0a4-cfaf36513290)|![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/26327506/ab76cf78-d712-4450-8488-37753263a917)|

Atualiza título na home do QD-Edu

---

src/assets/pages/available-cities.json
src/assets/pages/home.json
src/assets/pages/notifications.json

Atualiza site por conta da adição das cidades da Paulínia-SP e Barreiras-BA

Adiciona 2 novas cidades (jul/23)

---

src/app/interfaces/gazette.ts
src/app/modules/pages/search/search.component.html
src/app/services/gazette/gazette.service.spec.ts
src/app/services/gazette/gazette.service.ts

Resolve #73 
> Infelizmente não foi possível realizar a sua busca no momento.
> 
> Um problema com a nossa base de documentos ou com a sua conexão impediu a conclusão da pesquisa.
> 
> Verifique seu acesso à internet e tente novamente, ou refaça sua busca mais tarde.

Aplica tratamento de erro da API mostrando uma mensagem na tela

---

src/assets/pages/home.json
src/assets/pages/notifications.json

Atualiza site do projeto para registrar a adição de 12 novas cidades: 
- Osasco (SP)
- Nossa Senhora do Socorro (SE)
- Betim (MG)
- Canudos (BA)
- Mascote (BA)
- Salinas (MG)
- Votorantim (SP)
- Piedade (SP)
- Adolfo (SP)
- Guaraçaí (SP)
- Santana do Araguaia (PA)
- Gurupi (TO)
Este PR está bloqueado aguardando a integração do PR https://github.com/okfn-brasil/querido-diario/pull/910. Deve ser integrado a partir da outra semana, em alinhamento com o material de comemoração ao QD ter atingido o marco de 100 cidades.

Adiciona 12 novas cidades

---

src/assets/pages/about-education.json
src/assets/pages/home-education.json
src/assets/pages/home.json

Corrige link do ICICT

---

src/assets/pages/home.json
src/assets/pages/notifications.json

Atualiza `home` e `notifications` por conta das novas cidades: Itapetinga (BA), Santo Estevão (BA), Candeias (MG), Carmo da Cachoeira (MG), Jaboti (PR), Vera Cruz (RS), Vera Cruz (SP), São Roque (SP)

Atualiza site para informar 8 novas cidades

---

src/app/modules/components/search-form/search-form.component.sass
src/app/modules/pages/suggestion/suggestion.component.html

Corrige o tamanho do campo de filtro de período

---

src/app/modules/pages/area-education/home/home.component.html
src/app/modules/pages/area-education/home/home.component.sass
src/assets/pages/education-cases.json
src/assets/pages/home-education.json

Adiciona Caso #01

---

src/assets/pages/home.json
src/assets/pages/notifications.json

Atualiza site devido entrada de novas cidades

---

src/assets/pages/home.json
src/assets/pages/notifications.json

https://github.com/okfn-brasil/querido-diario/pull/952
https://github.com/okfn-brasil/querido-diario/pull/957

Atualiza dados no site devido entrada de 10 novas cidades

---

src/assets/pages/home.json
src/assets/pages/notifications.json

https://github.com/okfn-brasil/querido-diario/issues/950
https://github.com/okfn-brasil/querido-diario/issues/948

Atualiza dados no site

---

src/app/modules/components/date-picker-range/date-picker-range.component.ts
src/app/modules/components/search-form/search-form.component.ts

Resolve #162, #101, #158
| Antes | Depois |
|--------|--------|
| <b>Busca</b><br/>  ![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/42525687/f6e42120-cb76-408c-9b14-f75178a87917) |<br/><b>Busca</b><br/>  ![Group 1 (1)](https://github.com/okfn-brasil/querido-diario-frontend/assets/42525687/fc1f6f0a-2ac5-4504-9bcf-b16cb4ddc6b4) |
| <b>Busca Refeita</b><br/> ![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/42525687/045f7ac3-7a26-4896-9d0b-d4c88d0a0e47) | <b>Busca Refeita</b><br/> ![Group 2 (3)](https://github.com/okfn-brasil/querido-diario-frontend/assets/42525687/7e56dabd-2f5e-4c71-9b85-063d927f …

Issue#162 Bug filtro ordenação

---

src/app/modules/components/date-picker-range/date-picker-range.component.html
src/app/modules/components/date-picker-range/date-picker-range.component.ts

 Limita a data de fim do campo de período ao ano atual

---

src/assets/pages/education-cases.json

Adiciona Caso 02

---

docs/README.md

Corrige o link quebrado "Para mais detalhes ou informações..."
(um tópico de `CONTRIBUTING.md`) no arquivo `/docs/README.md` do repositório, quando renderizado na página inicial do repositório.
**Essa é uma _solução de contorno_, enquanto o Github não resolve o bug
descrito em:**  https://github.com/orgs/community/discussions/67750
Resolve https://github.com/okfn-brasil/querido-diario-frontend/issues/210

Corrige link quebrado "Para mais detalhes ou informações..."

---

src/assets/pages/education-cases.json

Adiciona Caso 03

---

src/assets/pages/home.json
src/assets/pages/notifications.json

Atualiza dados da plataforma

---

src/assets/pages/home.json
src/assets/pages/notifications.json

Atualiza dados do site (outubro/2023)

---

src/app/modules/components/notifications/notifications.component.html
src/assets/pages/notifications.json

Adapta componente notifications para permitir tags HTML

---

src/assets/pages/home.json
src/assets/pages/notifications.json

Adiciona informações relacionas as novas cidades dos PRs https://github.com/okfn-brasil/querido-diario/pull/937 e https://github.com/okfn-brasil/querido-diario/pull/954

Atualiza site com entrada de novas cidades

---

src/assets/pages/available-cities.json

Adiciona Bacuri(MA) a lista de cidades com publicação interrompida

---

src/assets/pages/home.json
src/assets/pages/notifications.json

https://github.com/okfn-brasil/querido-diario-data-processing/pull/64
https://github.com/okfn-brasil/querido-diario/pull/1059

Atualiza dados do site devido entrada de cidades de Alagoas (AMA)

---

src/assets/pages/home-education.json

Modifica nomenclatura de "Análises periódicas" > "Análises"

---

src/assets/pages/home.json
src/assets/pages/notifications.json

Realiza atualizações no site devido entrada de novas cidades 

---

src/robots.txt

Adicionando robots.txt

---

docs/README.md

Resolve #251 - Corrige direcionamento para o package.json

---

.github/PULL_REQUEST_TEMPLATE.md
docs/CODE_OF_CONDUCT-en-US.md
docs/CODE_OF_CONDUCT.md
docs/CONTRIBUTING-en-US.md
docs/CONTRIBUTING.md
docs/README.md
src/app/modules/pages/area-education/alerts/alerts.component.html
src/assets/pages/glossary.json
src/assets/pages/privacy-en_US.json
src/assets/pages/privacy.json
src/assets/pages/tech-en_US/documentation.json
src/assets/pages/tech/documentation.json

Atualiza informações na documentação local e do site

---

src/app/modules/pages/area-education/search/search.component.sass
src/app/modules/pages/search/search.component.sass

Corrige espaçamento quando não há conteúdo nos resultados

---

src/assets/pages/notifications.json
src/assets/pages/support/community.json

Atualiza informações do site

---

src/app/modules/pages/available-cities/available-cities.component.html
src/app/modules/pages/available-cities/available-cities.component.sass

Melhora responsividade do dashboard de cobertura

---

src/assets/pages/home.json
src/assets/pages/notifications.json

Atualiza notificações do site para listar as novas cidades
e Atualiza a quantidade de diários do QD

Atualiza contadores do site

---

src/app/modules/pages/area-education/search/filters/city-filter/city-filter.component.html
src/app/modules/pages/area-education/search/filters/city-filter/city-filter.component.sass
src/app/modules/pages/area-education/search/filters/city-filter/city-filter.component.ts

Correção da exibição do dropdown de cidades

---

src/app/modules/components/card/card.component.sass
src/app/modules/components/carousel/carousel.component.html
src/app/modules/components/carousel/carousel.component.sass
src/app/modules/components/goals/goals.component.html
src/app/modules/pages/support/support.component.html
src/assets/pages/our-goals.json

Habilita carrossel de metas de financiamento coletivo

---

src/app/modules/pages/area-education/search/filters/city-filter/city-filter.component.ts
src/app/modules/pages/area-education/search/search.component.sass

…icípio
Resolve #306 
Resolve #315 
Antes:
Depois:

Corrige placeholder sobrepondo texto no campo de município no QD edu

---

src/app/modules/components/header/header.component.html
src/app/modules/components/header/header.component.ts
src/app/modules/components/notifications/notifications.component.sass

Usando como referência o "botão"
#307 
Antes:
Depois:
https://github.com/user-attachments/assets/3d2bd9e0-e616-438b-b7ea-ea62d9d2b9b7

fix: Posicionamento dialog notificacao

---

src/app/app.component.html
src/index.html

https://github.com/okfn-brasil/querido-diario-frontend/pull/313#issuecomment-2628551066
https://www.opengraph.xyz/url/https%3A%2F%2Fdeploy-preview-333--querido-diario-plataforma.netlify.app

Transfere meta tags para preview do site

---

src/app/modules/pages/blog/blog-list/blog-list.component.ts

🐛 bugfix(blog-list.component.ts): Ajusta para sempre voltar à página 1

---

src/app/modules/components/cities-search-result/cities-search-result.component.html

🔧 chore(cities-search-result.component.html): Adiciona target='_blank' nos links

---

src/assets/i18n/en/home.json
src/assets/i18n/pt/home.json

Adiciona solução provisória para #358 
Antes: 
Depois:

Adiciona contador de cidades na homepage

---

src/assets/i18n/en/global.json
src/assets/i18n/pt/global.json

Melhora texto do botão de doar no cabeçalho

---

src/app/modules/pages/area-education/signup/signup.component.html

🐛 fix(issue_350): Adiciona links faltantes nos Termos e Condições e Fale Conosco

---

src/app/modules/components/header/header.component.html

Alterando o endereço de destino do botão Apoie

---

src/app/modules/components/header/header.component.html

Reverts okfn-brasil/querido-diario-frontend#371

Revert "Alterando o endereço de destino do botão Apoie"
